---
title: "tidycensus assignment"
author: "randi delong"
format: html
---

## Assignment for Week 10: Databases and APIs

```{r}
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(scales)
options(tigris_use_cache = TRUE)

census_api_key("6cba154bc2b13dd1269b03f924d613b6b7c6cf11")
#don't store in code in future
#use Renviron file 

acs23 <- load_variables(2023, "acs5", cache = TRUE)

table(acs23$geography)

#limiting to variables at geography level smaller than state
acs23 <- acs23 %>%  
  filter(geography %in% c("county","block group"))

#Field of Bachelor's Degree for First Major for the Population 25 Years and Over
bach_vars <- c(total = "C15010_001",
            engineer = "C15010_002",
            engineer2 = "C15010_003", 
            business = "C15010_004", 
            education = "C15010_005", 
            arts = "C15010_006")

bach_type <- get_acs(
  geography = "county", 
  variables = bach_vars,
  state = "NC",
  geometry = TRUE,
  year = 2023, 
) 

#proportion of the population over 25 with a bachelor's degree whose first major was engineering 
bach_type_wide <- bach_type %>% 
  select(GEOID, NAME, geometry, variable, estimate) %>% 
  pivot_wider(names_from = variable, values_from = estimate) %>%  
  mutate(eng_prop = ((engineer+engineer2)/total)) 

bach_type_wide %>% 
    ggplot(aes(fill = eng_prop)) + 
    geom_sf(color = NA) + 
    theme_void() + 
    scale_fill_viridis_c(labels = scales::percent_format()) +
    labs(title = "Proportion of Science and Engineering Degrees", 
         subtitle = "North Carolina, Age 25+")

```

What does the Triangle look like more specifically?

```{r}
triangle <- c("Wake", "Orange", "Durham")

bach_type_tri <- get_acs(
  geography = "tract", 
  variables = bach_vars,
  state = "NC",
  county = triangle, 
  geometry = TRUE,
  year = 2023, 
) 

bach_type_tri <- bach_type_tri %>%  
  filter(variable %in% c("engineer", "total"))

bach_type_tri_wide <- bach_type_tri %>% 
  select(GEOID, NAME, geometry, variable, estimate) %>% 
  pivot_wider(names_from = variable, values_from = estimate) %>%  
  mutate(eng_prop = engineer/total) 

bach_type_tri_wide %>% 
    ggplot(aes(fill = eng_prop)) + 
    geom_sf(color = NA) + 
    theme_void() + 
    scale_fill_viridis_c(labels = scales::percent_format()) +
    labs(title = "Proportion of Engineering Degrees", 
         subtitle = "Age 25 and over")

cities <- places(state = c("NC"), cb = FALSE)
triangle_cities <- cities %>%
  filter(NAME %in% c("Raleigh", "Durham", "Chapel Hill", "Cary", "Apex", "Morrisville"))


triangle_pts <- triangle_cities %>% st_centroid()

ggplot() +
  geom_sf(data = bach_type_tri_wide, aes(fill = eng_prop), color = "white", size = 0.3) +
  geom_sf(data = triangle_pts, color = "black", size = 1) +
  geom_text_repel(
    data = triangle_pts,
    aes(label = NAME, geometry = geometry),
    stat = "sf_coordinates",
    size = 6
  ) +
  theme_void() +
  coord_sf(xlim = c(-79.3, -78.3), ylim = c(35.6, 36.2)) +
  scale_fill_viridis_c(labels = scales::percent_format()) +
  labs(
    title = "Proportion of Engineering Degrees",
    subtitle = "Age 25 and over (Triangle Region)"
  )
  
```
